import { Deck } from './types';

// Large dataset separated into chunks for better organization
export const STARTER_DECKS: Deck[] = [
  {
    id: 'common-1',
    name: 'Temel Kelimeler (1-50)',
    description: 'Günlük hayatta en sık kullanılan ilk 50 kelime.',
    words: [
      { id: '1', en: 'Time', tr: 'Zaman', exampleEn: 'Time flows like a river.', exampleTr: 'Zaman bir nehir gibi akar.' },
      { id: '2', en: 'Person', tr: 'Kişi', exampleEn: 'He is a nice person.', exampleTr: 'O iyi bir kişidir.' },
      { id: '3', en: 'Year', tr: 'Yıl', exampleEn: 'Happy new year!', exampleTr: 'Mutlu yıllar!' },
      { id: '4', en: 'Way', tr: 'Yol / Yöntem', exampleEn: 'Show me the way.', exampleTr: 'Bana yolu göster.' },
      { id: '5', en: 'Day', tr: 'Gün', exampleEn: 'Have a nice day.', exampleTr: 'İyi günler.' },
      { id: '6', en: 'Thing', tr: 'Şey', exampleEn: 'That is a strange thing.', exampleTr: 'Bu garip bir şey.' },
      { id: '7', en: 'Man', tr: 'Adam', exampleEn: 'The man is tall.', exampleTr: 'Adam uzun boylu.' },
      { id: '8', en: 'World', tr: 'Dünya', exampleEn: 'The world is round.', exampleTr: 'Dünya yuvarlaktır.' },
      { id: '9', en: 'Life', tr: 'Hayat', exampleEn: 'Life is beautiful.', exampleTr: 'Hayat güzeldir.' },
      { id: '10', en: 'Hand', tr: 'El', exampleEn: 'Give me your hand.', exampleTr: 'Elini bana ver.' },
      { id: '11', en: 'Part', tr: 'Parça / Bölüm', exampleEn: 'This is the best part.', exampleTr: 'Bu en iyi bölüm.' },
      { id: '12', en: 'Child', tr: 'Çocuk', exampleEn: 'The child is playing.', exampleTr: 'Çocuk oynuyor.' },
      { id: '13', en: 'Eye', tr: 'Göz', exampleEn: 'She has blue eyes.', exampleTr: 'Onun mavi gözleri var.' },
      { id: '14', en: 'Woman', tr: 'Kadın', exampleEn: 'That woman is a doctor.', exampleTr: 'O kadın bir doktor.' },
      { id: '15', en: 'Place', tr: 'Yer', exampleEn: 'This is a nice place.', exampleTr: 'Burası güzel bir yer.' },
      { id: '16', en: 'Work', tr: 'İş / Çalışmak', exampleEn: 'I have a lot of work.', exampleTr: 'Çok işim var.' },
      { id: '17', en: 'Week', tr: 'Hafta', exampleEn: 'See you next week.', exampleTr: 'Haftaya görüşürüz.' },
      { id: '18', en: 'Case', tr: 'Durum / Dava', exampleEn: 'In that case, we leave.', exampleTr: 'O durumda, biz gideriz.' },
      { id: '19', en: 'Point', tr: 'Nokta / Puan', exampleEn: 'What is your point?', exampleTr: 'Amacın (noktan) ne?' },
      { id: '20', en: 'Government', tr: 'Hükümet', exampleEn: 'The government made a law.', exampleTr: 'Hükümet bir yasa yaptı.' },
      { id: '21', en: 'Company', tr: 'Şirket', exampleEn: 'He works for a big company.', exampleTr: 'Büyük bir şirkette çalışıyor.' },
      { id: '22', en: 'Number', tr: 'Sayı / Numara', exampleEn: 'What is your phone number?', exampleTr: 'Telefon numaran nedir?' },
      { id: '23', en: 'Group', tr: 'Grup', exampleEn: 'A group of people arrived.', exampleTr: 'Bir grup insan geldi.' },
      { id: '24', en: 'Problem', tr: 'Sorun', exampleEn: 'We have a big problem.', exampleTr: 'Büyük bir sorunumuz var.' },
      { id: '25', en: 'Fact', tr: 'Gerçek', exampleEn: 'It is a known fact.', exampleTr: 'Bu bilinen bir gerçektir.' },
      { id: '26', en: 'To Be', tr: 'Olmak', exampleEn: 'I want to be happy.', exampleTr: 'Mutlu olmak istiyorum.' },
      { id: '27', en: 'To Have', tr: 'Sahip olmak', exampleEn: 'I have a car.', exampleTr: 'Bir arabam var.' },
      { id: '28', en: 'To Do', tr: 'Yapmak', exampleEn: 'I will do my best.', exampleTr: 'Elimden geleni yapacağım.' },
      { id: '29', en: 'To Say', tr: 'Söylemek', exampleEn: 'What did you say?', exampleTr: 'Ne söyledin?' },
      { id: '30', en: 'To Get', tr: 'Almak / Elde etmek', exampleEn: 'I need to get some sleep.', exampleTr: 'Biraz uyumam (uyku almam) lazım.' },
      { id: '31', en: 'To Make', tr: 'Yapmak (Üretmek)', exampleEn: 'She makes delicious cakes.', exampleTr: 'O lezzetli kekler yapar.' },
      { id: '32', en: 'To Go', tr: 'Gitmek', exampleEn: 'Let\'s go home.', exampleTr: 'Hadi eve gidelim.' },
      { id: '33', en: 'To Know', tr: 'Bilmek', exampleEn: 'I know the answer.', exampleTr: 'Cevabı biliyorum.' },
      { id: '34', en: 'To Take', tr: 'Almak / Götürmek', exampleEn: 'Take this book.', exampleTr: 'Bu kitabı al.' },
      { id: '35', en: 'To See', tr: 'Görmek', exampleEn: 'I can see the sea.', exampleTr: 'Denizi görebiliyorum.' },
      { id: '36', en: 'To Come', tr: 'Gelmek', exampleEn: 'Come here, please.', exampleTr: 'Buraya gel, lütfen.' },
      { id: '37', en: 'To Think', tr: 'Düşünmek', exampleEn: 'I think it will rain.', exampleTr: 'Sanırım (düşünüyorum) yağmur yağacak.' },
      { id: '38', en: 'To Look', tr: 'Bakmak', exampleEn: 'Look at the sky.', exampleTr: 'Gökyüzüne bak.' },
      { id: '39', en: 'To Want', tr: 'İstemek', exampleEn: 'I want some water.', exampleTr: 'Biraz su istiyorum.' },
      { id: '40', en: 'To Give', tr: 'Vermek', exampleEn: 'Give me a chance.', exampleTr: 'Bana bir şans ver.' },
      { id: '41', en: 'Good', tr: 'İyi', exampleEn: 'This is a good book.', exampleTr: 'Bu iyi bir kitap.' },
      { id: '42', en: 'New', tr: 'Yeni', exampleEn: 'I bought a new phone.', exampleTr: 'Yeni bir telefon aldım.' },
      { id: '43', en: 'First', tr: 'İlk', exampleEn: 'She was the first to arrive.', exampleTr: 'O ilk varandı.' },
      { id: '44', en: 'Last', tr: 'Son', exampleEn: 'This is the last bus.', exampleTr: 'Bu son otobüs.' },
      { id: '45', en: 'Long', tr: 'Uzun', exampleEn: 'It was a long journey.', exampleTr: 'Uzun bir yolculuktu.' },
      { id: '46', en: 'Great', tr: 'Harika / Büyük', exampleEn: 'You did a great job.', exampleTr: 'Harika bir iş çıkardın.' },
      { id: '47', en: 'Little', tr: 'Küçük / Az', exampleEn: 'I have a little money.', exampleTr: 'Az param var.' },
      { id: '48', en: 'Own', tr: 'Kendi', exampleEn: 'I have my own room.', exampleTr: 'Kendi odam var.' },
      { id: '49', en: 'Other', tr: 'Diğer', exampleEn: 'Show me the other hand.', exampleTr: 'Diğer elini göster.' },
      { id: '50', en: 'Old', tr: 'Eski / Yaşlı', exampleEn: 'My car is very old.', exampleTr: 'Arabam çok eski.' },
    ]
  },
  {
    id: 'common-2',
    name: 'Orta Seviye Kelimeler',
    description: 'Kendinizi daha iyi ifade etmeniz için gerekenler.',
    words: [
      { id: '51', en: 'Right', tr: 'Doğru / Sağ', exampleEn: 'You are right.', exampleTr: 'Haklısın (Doğrusun).' },
      { id: '52', en: 'Big', tr: 'Büyük', exampleEn: 'New York is a big city.', exampleTr: 'New York büyük bir şehirdir.' },
      { id: '53', en: 'High', tr: 'Yüksek', exampleEn: 'The prices are very high.', exampleTr: 'Fiyatlar çok yüksek.' },
      { id: '54', en: 'Different', tr: 'Farklı', exampleEn: 'I want something different.', exampleTr: 'Farklı bir şey istiyorum.' },
      { id: '55', en: 'Small', tr: 'Küçük', exampleEn: 'The apartment is small.', exampleTr: 'Daire küçük.' },
      { id: '56', en: 'Large', tr: 'Geniş / Büyük', exampleEn: 'They have a large family.', exampleTr: 'Geniş bir aileleri var.' },
      { id: '57', en: 'Next', tr: 'Sonraki', exampleEn: 'See you next time.', exampleTr: 'Bir dahaki sefere görüşürüz.' },
      { id: '58', en: 'Early', tr: 'Erken', exampleEn: 'I woke up early today.', exampleTr: 'Bugün erken uyandım.' },
      { id: '59', en: 'Young', tr: 'Genç', exampleEn: 'He is a young man.', exampleTr: 'O genç bir adam.' },
      { id: '60', en: 'Important', tr: 'Önemli', exampleEn: 'This is an important meeting.', exampleTr: 'Bu önemli bir toplantı.' },
      { id: '61', en: 'Few', tr: 'Az / Birkaç', exampleEn: 'I have a few questions.', exampleTr: 'Birkaç sorum var.' },
      { id: '62', en: 'Public', tr: 'Halka açık / Kamu', exampleEn: 'This is a public park.', exampleTr: 'Bu halka açık bir park.' },
      { id: '63', en: 'Bad', tr: 'Kötü', exampleEn: 'The weather is bad.', exampleTr: 'Hava kötü.' },
      { id: '64', en: 'Same', tr: 'Aynı', exampleEn: 'We have the same car.', exampleTr: 'Aynı arabaya sahibiz.' },
      { id: '65', en: 'Able', tr: 'Muktedir / Yapabilir', exampleEn: 'Will you be able to come?', exampleTr: 'Gelebilecek misin?' },
      { id: '66', en: 'To Use', tr: 'Kullanmak', exampleEn: 'Can I use your phone?', exampleTr: 'Telefonunu kullanabilir miyim?' },
      { id: '67', en: 'To Find', tr: 'Bulmak', exampleEn: 'I cannot find my keys.', exampleTr: 'Anahtarlarımı bulamıyorum.' },
      { id: '68', en: 'To Tell', tr: 'Anlatmak / Söylemek', exampleEn: 'Tell me the truth.', exampleTr: 'Bana gerçeği söyle.' },
      { id: '69', en: 'To Ask', tr: 'Sormak / İstemek', exampleEn: 'Can I ask a question?', exampleTr: 'Bir soru sorabilir miyim?' },
      { id: '70', en: 'To Work', tr: 'Çalışmak', exampleEn: 'She works at a bank.', exampleTr: 'O bir bankada çalışıyor.' },
      { id: '71', en: 'To Seem', tr: 'Görünmek', exampleEn: 'You seem tired.', exampleTr: 'Yorgun görünüyorsun.' },
      { id: '72', en: 'To Feel', tr: 'Hissetmek', exampleEn: 'I feel much better.', exampleTr: 'Çok daha iyi hissediyorum.' },
      { id: '73', en: 'To Try', tr: 'Denemek', exampleEn: 'Try to do it again.', exampleTr: 'Tekrar yapmayı dene.' },
      { id: '74', en: 'To Leave', tr: 'Ayrılmak / Bırakmak', exampleEn: 'Don\'t leave me alone.', exampleTr: 'Beni yalnız bırakma.' },
      { id: '75', en: 'To Call', tr: 'Aramak / Çağırmak', exampleEn: 'Call me later.', exampleTr: 'Beni sonra ara.' },
      { id: '76', en: 'Beneath', tr: 'Altında', exampleEn: 'The boat sank beneath the waves.', exampleTr: 'Tekne dalgaların altına battı.' },
      { id: '77', en: 'Education', tr: 'Eğitim', exampleEn: 'Education is very important.', exampleTr: 'Eğitim çok önemlidir.' },
      { id: '78', en: 'Opportunity', tr: 'Fırsat', exampleEn: 'Don\'t miss this opportunity.', exampleTr: 'Bu fırsatı kaçırma.' },
      { id: '79', en: 'Society', tr: 'Toplum', exampleEn: 'We live in a society.', exampleTr: 'Bir toplumda yaşıyoruz.' },
      { id: '80', en: 'Process', tr: 'Süreç', exampleEn: 'Learning is a slow process.', exampleTr: 'Öğrenme yavaş bir süreçtir.' },
      { id: '81', en: 'Voice', tr: 'Ses', exampleEn: 'She has a beautiful voice.', exampleTr: 'Onun güzel bir sesi var.' },
      { id: '82', en: 'Value', tr: 'Değer', exampleEn: 'What is the value of this?', exampleTr: 'Bunun değeri nedir?' },
      { id: '83', en: 'Action', tr: 'Eylem / Hareket', exampleEn: 'Take action now.', exampleTr: 'Şimdi harekete geç.' },
      { id: '84', en: 'Area', tr: 'Alan / Bölge', exampleEn: 'This is a restricted area.', exampleTr: 'Bu yasaklanmış bir bölge.' },
      { id: '85', en: 'Evidence', tr: 'Kanıt', exampleEn: 'There is no evidence.', exampleTr: 'Hiçbir kanıt yok.' },
      { id: '86', en: 'Effect', tr: 'Etki', exampleEn: 'The medicine had no effect.', exampleTr: 'İlacın hiçbir etkisi olmadı.' },
      { id: '87', en: 'Support', tr: 'Destek', exampleEn: 'I need your support.', exampleTr: 'Desteğine ihtiyacım var.' },
      { id: '88', en: 'Moment', tr: 'An', exampleEn: 'Wait a moment.', exampleTr: 'Bir saniye bekle.' },
      { id: '89', en: 'Sense', tr: 'His / Duyu', exampleEn: 'It makes no sense.', exampleTr: 'Bunun hiçbir mantığı yok.' },
      { id: '90', en: 'Material', tr: 'Malzeme', exampleEn: 'What material is this?', exampleTr: 'Bu hangi malzeme?' },
    ]
  },
  {
    id: 'common-3',
    name: 'İleri Seviye Kelimeler',
    description: 'Akademik ve profesyonel kelimeler.',
    words: [
      { id: '91', en: 'To Provide', tr: 'Sağlamak / Temin etmek', exampleEn: 'We provide food for the poor.', exampleTr: 'Fakirlere yemek sağlıyoruz.' },
      { id: '92', en: 'To Include', tr: 'İçermek', exampleEn: 'The price includes breakfast.', exampleTr: 'Fiyata kahvaltı dahildir.' },
      { id: '93', en: 'To Continue', tr: 'Devam etmek', exampleEn: 'Please continue working.', exampleTr: 'Lütfen çalışmaya devam edin.' },
      { id: '94', en: 'To Set', tr: 'Ayarlamak / Kurmak', exampleEn: 'Set the alarm for 7 AM.', exampleTr: 'Alarmı sabah 7\'ye kur.' },
      { id: '95', en: 'To Learn', tr: 'Öğrenmek', exampleEn: 'I want to learn English.', exampleTr: 'İngilizce öğrenmek istiyorum.' },
      { id: '96', en: 'To Change', tr: 'Değiştirmek', exampleEn: 'You cannot change the past.', exampleTr: 'Geçmişi değiştiremezsin.' },
      { id: '97', en: 'To Lead', tr: 'Yönetmek / Öncülük etmek', exampleEn: 'Who will lead the team?', exampleTr: 'Takıma kim liderlik edecek?' },
      { id: '98', en: 'To Understand', tr: 'Anlamak', exampleEn: 'Do you understand me?', exampleTr: 'Beni anlıyor musun?' },
      { id: '99', en: 'To Watch', tr: 'İzlemek', exampleEn: 'We watched a movie.', exampleTr: 'Bir film izledik.' },
      { id: '100', en: 'To Follow', tr: 'Takip etmek', exampleEn: 'Follow the car.', exampleTr: 'Arabayı takip et.' },
      { id: '101', en: 'Result', tr: 'Sonuç', exampleEn: 'The result was good.', exampleTr: 'Sonuç iyiydi.' },
      { id: '102', en: 'Development', tr: 'Gelişim', exampleEn: 'Economic development is slow.', exampleTr: 'Ekonomik gelişim yavaş.' },
      { id: '103', en: 'Decision', tr: 'Karar', exampleEn: 'Make a decision.', exampleTr: 'Bir karar ver.' },
      { id: '104', en: 'Position', tr: 'Pozisyon / Konum', exampleEn: 'What is your position in the company?', exampleTr: 'Şirketteki pozisyonun nedir?' },
      { id: '105', en: 'Relationship', tr: 'İlişki', exampleEn: 'They have a good relationship.', exampleTr: 'İyi bir ilişkileri var.' },
      { id: '106', en: 'Major', tr: 'Ana / Büyük', exampleEn: 'This is a major problem.', exampleTr: 'Bu büyük bir sorun.' },
      { id: '107', en: 'Specific', tr: 'Belirli / Özel', exampleEn: 'Be more specific.', exampleTr: 'Daha belirgin ol.' },
      { id: '108', en: 'International', tr: 'Uluslararası', exampleEn: 'It is an international airport.', exampleTr: 'O uluslararası bir havaalanı.' },
      { id: '109', en: 'Effective', tr: 'Etkili', exampleEn: 'The medicine is effective.', exampleTr: 'İlaç etkili.' },
      { id: '110', en: 'Various', tr: 'Çeşitli', exampleEn: 'There are various reasons.', exampleTr: 'Çeşitli sebepler var.' },
    ]
  },
  {
    id: 'verbs-1',
    name: 'Fiiller (Verbs)',
    description: 'Hareket ve eylem bildiren kelimeler.',
    words: [
       { id: 'v1', en: 'Accept', tr: 'Kabul etmek', exampleEn: 'She accepted the gift.', exampleTr: 'Hediyeyi kabul etti.' },
       { id: 'v2', en: 'Achieve', tr: 'Başarmak', exampleEn: 'You can achieve your goals.', exampleTr: 'Hedeflerini başarabilirsin.' },
       { id: 'v3', en: 'Admit', tr: 'İtiraf etmek', exampleEn: 'He admitted his mistake.', exampleTr: 'Hatasını itiraf etti.' },
       { id: 'v4', en: 'Affect', tr: 'Etkilemek', exampleEn: 'The weather affects my mood.', exampleTr: 'Hava ruh halimi etkiler.' },
       { id: 'v5', en: 'Afford', tr: 'Gücü yetmek (maddi)', exampleEn: 'I can\'t afford this car.', exampleTr: 'Bu arabaya gücüm yetmez.' },
       { id: 'v6', en: 'Agree', tr: 'Katılmak / Anlaşmak', exampleEn: 'I agree with you.', exampleTr: 'Sana katılıyorum.' },
       { id: 'v7', en: 'Allow', tr: 'İzin vermek', exampleEn: 'Pets are not allowed.', exampleTr: 'Evcil hayvanlara izin verilmez.' },
       { id: 'v8', en: 'Answer', tr: 'Cevap vermek', exampleEn: 'Answer the question.', exampleTr: 'Soruyu cevapla.' },
       { id: 'v9', en: 'Apply', tr: 'Başvurmak / Uygulamak', exampleEn: 'Apply for the job.', exampleTr: 'İşe başvur.' },
       { id: 'v10', en: 'Argue', tr: 'Tartışmak', exampleEn: 'They argue all the time.', exampleTr: 'Sürekli tartışıyorlar.' },
       { id: 'v11', en: 'Arrive', tr: 'Varmak', exampleEn: 'We arrived late.', exampleTr: 'Geç vardık.' },
       { id: 'v12', en: 'Assume', tr: 'Varsaymak', exampleEn: 'I assume you are busy.', exampleTr: 'Meşgul olduğunu varsayıyorum.' },
       { id: 'v13', en: 'Attack', tr: 'Saldırmak', exampleEn: 'The dog attacked him.', exampleTr: 'Köpek ona saldırdı.' },
       { id: 'v14', en: 'Avoid', tr: 'Kaçınmak', exampleEn: 'Avoid junk food.', exampleTr: 'Abur cuburdan kaçın.' },
       { id: 'v15', en: 'Become', tr: 'Olmak / Dönüşmek', exampleEn: 'She became a doctor.', exampleTr: 'O doktor oldu.' },
       { id: 'v16', en: 'Begin', tr: 'Başlamak', exampleEn: 'Let\'s begin the meeting.', exampleTr: 'Toplantıya başlayalım.' },
       { id: 'v17', en: 'Believe', tr: 'İnanmak', exampleEn: 'I believe in you.', exampleTr: 'Sana inanıyorum.' },
       { id: 'v18', en: 'Build', tr: 'İnşa etmek', exampleEn: 'They built a house.', exampleTr: 'Bir ev inşa ettiler.' },
       { id: 'v19', en: 'Buy', tr: 'Satın almak', exampleEn: 'I want to buy bread.', exampleTr: 'Ekmek satın almak istiyorum.' },
       { id: 'v20', en: 'Care', tr: 'Umursamak / Bakım yapmak', exampleEn: 'I don\'t care.', exampleTr: 'Umurumda değil.' },
    ]
  },
  {
    id: 'adjectives-1',
    name: 'Sıfatlar (Adjectives)',
    description: 'Niteleme ve betimleme kelimeleri.',
    words: [
      { id: 'a1', en: 'Available', tr: 'Mevcut / Müsait', exampleEn: 'Is this seat available?', exampleTr: 'Bu koltuk müsait mi?' },
      { id: 'a2', en: 'Beautiful', tr: 'Güzel', exampleEn: 'It is a beautiful day.', exampleTr: 'Güzel bir gün.' },
      { id: 'a3', en: 'Best', tr: 'En iyi', exampleEn: 'He is my best friend.', exampleTr: 'O benim en iyi arkadaşım.' },
      { id: 'a4', en: 'Better', tr: 'Daha iyi', exampleEn: 'I feel better now.', exampleTr: 'Şimdi daha iyi hissediyorum.' },
      { id: 'a5', en: 'Black', tr: 'Siyah', exampleEn: 'She wore a black dress.', exampleTr: 'Siyah bir elbise giydi.' },
      { id: 'a6', en: 'Blue', tr: 'Mavi', exampleEn: 'The sky is blue.', exampleTr: 'Gökyüzü mavi.' },
      { id: 'a7', en: 'Boring', tr: 'Sıkıcı', exampleEn: 'The movie was boring.', exampleTr: 'Film sıkıcıydı.' },
      { id: 'a8', en: 'Brave', tr: 'Cesur', exampleEn: 'He is a brave soldier.', exampleTr: 'O cesur bir asker.' },
      { id: 'a9', en: 'Bright', tr: 'Parlak / Zeki', exampleEn: 'The sun is bright.', exampleTr: 'Güneş parlak.' },
      { id: 'a10', en: 'Busy', tr: 'Meşgul', exampleEn: 'I am very busy.', exampleTr: 'Çok meşgulüm.' },
      { id: 'a11', en: 'Calm', tr: 'Sakin', exampleEn: 'Stay calm.', exampleTr: 'Sakin ol.' },
      { id: 'a12', en: 'Careful', tr: 'Dikkatli', exampleEn: 'Be careful driving.', exampleTr: 'Araba sürerken dikkatli ol.' },
      { id: 'a13', en: 'Certain', tr: 'Kesin', exampleEn: 'Are you certain?', exampleTr: 'Emin misin?' },
      { id: 'a14', en: 'Cheap', tr: 'Ucuz', exampleEn: 'This shirt is cheap.', exampleTr: 'Bu gömlek ucuz.' },
      { id: 'a15', en: 'Clean', tr: 'Temiz', exampleEn: 'Keep your room clean.', exampleTr: 'Odanı temiz tut.' },
      { id: 'a16', en: 'Clear', tr: 'Net / Açık', exampleEn: 'The water is clear.', exampleTr: 'Su berrak.' },
      { id: 'a17', en: 'Close', tr: 'Yakın / Kapalı', exampleEn: 'They are close friends.', exampleTr: 'Onlar yakın arkadaşlar.' },
      { id: 'a18', en: 'Cold', tr: 'Soğuk', exampleEn: 'It is cold outside.', exampleTr: 'Dışarısı soğuk.' },
      { id: 'a19', en: 'Common', tr: 'Yaygın / Ortak', exampleEn: 'Smith is a common name.', exampleTr: 'Smith yaygın bir isimdir.' },
      { id: 'a20', en: 'Complete', tr: 'Tam / Eksiksiz', exampleEn: 'The work is complete.', exampleTr: 'İş tamamlandı.' },
    ]
  },
  {
    id: 'extended-list-1',
    name: 'Geniş Kelime Listesi (Fiiller & Akademik)',
    description: '300+ kelimelik kapsamlı çalışma listesi.',
    words: [
      { id: 'ex-1', en: 'Admit', tr: 'İtiraf etmek, kabul etmek' },
      { id: 'ex-2', en: 'Abandon', tr: 'Terk etmek' },
      { id: 'ex-3', en: 'Absorb', tr: 'Emmek, soğurmak' },
      { id: 'ex-4', en: 'Abuse', tr: 'Kötüye kullanmak' },
      { id: 'ex-5', en: 'Accelerate', tr: 'Hızlanmak, hızlandırmak' },
      { id: 'ex-6', en: 'Accept', tr: 'Kabul etmek' },
      { id: 'ex-7', en: 'Accommodate', tr: 'Uyum sağlamak, yerleştirmek' },
      { id: 'ex-8', en: 'Accompany', tr: 'Eşlik etmek' },
      { id: 'ex-9', en: 'Accomplish', tr: 'Sonuçlandırmak, başarıyla tamamlamak' },
      { id: 'ex-10', en: 'Accumulate', tr: 'Biriktirmek' },
      { id: 'ex-11', en: 'Accuse', tr: 'Suçlamak' },
      { id: 'ex-12', en: 'Achieve', tr: 'Başarmak' },
      { id: 'ex-13', en: 'Acknowledge', tr: 'Kabul etmek, kabullenmek, itiraf etmek' },
      { id: 'ex-14', en: 'Address', tr: 'Hitap etmek, söylev, adres' },
      { id: 'ex-15', en: 'Adjust', tr: 'Ayarlamak' },
      { id: 'ex-16', en: 'Administer', tr: 'Yönetmek, idare etmek' },
      { id: 'ex-17', en: 'Admire', tr: 'Hayranlık duymak' },
      { id: 'ex-18', en: 'Adopt', tr: 'Evlat edinmek, benimsemek' },
      { id: 'ex-19', en: 'Aggravate', tr: 'Kötüleştirmek, zorlaştırmak' },
      { id: 'ex-20', en: 'Agree', tr: 'Kabul etmek, anlaşmak' },
      { id: 'ex-21', en: 'Alienate', tr: 'Yabancılaştırmak' },
      { id: 'ex-22', en: 'Alleviate', tr: 'Hafifletmek, azaltmak' },
      { id: 'ex-23', en: 'Allocate', tr: 'Tahsis etmek, pay etmek' },
      { id: 'ex-24', en: 'Allow', tr: 'İzin vermek, müsaade etmek' },
      { id: 'ex-25', en: 'Alter', tr: 'Değiştirmek' },
      { id: 'ex-26', en: 'Appear', tr: 'Gibi görünmek, ortaya çıkmak' },
      { id: 'ex-27', en: 'Apply', tr: 'Başvurmak, uygulamak' },
      { id: 'ex-28', en: 'Appoint', tr: 'Atamak' },
      { id: 'ex-29', en: 'Appraise', tr: 'Değer biçmek, kıymet takdir etmek' },
      { id: 'ex-30', en: 'Appreciate', tr: 'Takdir etmek' },
      { id: 'ex-31', en: 'Approve', tr: 'Onaylamak' },
      { id: 'ex-32', en: 'Arise', tr: 'Meydana çıkmak' },
      { id: 'ex-33', en: 'Articulate', tr: 'Açıkça söylemek' },
      { id: 'ex-34', en: 'Assess', tr: 'Değerlendirmek, değer biçmek' },
      { id: 'ex-35', en: 'Attach', tr: 'Bağlamak, eklemek, iliştirmek' },
      { id: 'ex-36', en: 'Attain', tr: 'Elde etmek, erişmek' },
      { id: 'ex-37', en: 'Attribute', tr: 'Atfetmek, dayandırmak' },
      { id: 'ex-38', en: 'Avoid', tr: 'Kaçınmak' },
      { id: 'ex-39', en: 'Become', tr: 'Olmak' },
      { id: 'ex-40', en: 'Begin', tr: 'Başlamak, başlatmak' },
      { id: 'ex-41', en: 'Block', tr: 'Engellemek' },
      { id: 'ex-42', en: 'Blur', tr: 'Bulandırmak, lekelemek' },
      { id: 'ex-43', en: 'Boost', tr: 'Arttırmak, yükseltmek' },
      { id: 'ex-44', en: 'Capture', tr: 'Esir almak, ele geçirmek' },
      { id: 'ex-45', en: 'Celebrate', tr: 'Kutlamak' },
      { id: 'ex-46', en: 'Challenge', tr: 'Karşı çıkmak, meydan okumak' },
      { id: 'ex-47', en: 'Change', tr: 'Değişmek, değiştirmek' },
      { id: 'ex-48', en: 'Circulate', tr: 'Deveran etmek, dolaşmak' },
      { id: 'ex-49', en: 'Claim', tr: 'İddia etmek' },
      { id: 'ex-50', en: 'Collect', tr: 'Toplamak, biriktirmek' },
      { id: 'ex-51', en: 'Commit', tr: 'İşlemek (suç vb.)' },
      { id: 'ex-52', en: 'Compensate', tr: 'Telafi etmek, tazmin etmek' },
      { id: 'ex-53', en: 'Compete', tr: 'Rekabet etmek' },
      { id: 'ex-54', en: 'Compile', tr: 'Derlemek' },
      { id: 'ex-55', en: 'Complain', tr: 'Şikayet etmek' },
      { id: 'ex-56', en: 'Comprise', tr: 'Kapsamak, içermek' },
      { id: 'ex-57', en: 'Conceal', tr: 'Gizlemek, gizli tutmak' },
      { id: 'ex-58', en: 'Convey', tr: 'İletmek, aktarmak, göstermek' },
      { id: 'ex-59', en: 'Conduct', tr: 'Yönetmek, yürütmek' },
      { id: 'ex-60', en: 'Confirm', tr: 'Onaylamak, doğrulamak' },
      { id: 'ex-61', en: 'Confront', tr: 'Yüzleşmek, karşı karşıya olmak' },
      { id: 'ex-62', en: 'Confuse', tr: 'Kafasını karıştırmak' },
      { id: 'ex-63', en: 'Conquer', tr: 'Fethetmek, ele geçirmek' },
      { id: 'ex-64', en: 'Consider', tr: 'Göz önünde bulundurmak' },
      { id: 'ex-65', en: 'Constitute', tr: 'Oluşturmak, teşkil etmek' },
      { id: 'ex-66', en: 'Constrain', tr: 'Kısıtlamak, engellemek' },
      { id: 'ex-67', en: 'Construct', tr: 'İnşa etmek, kurmak' },
      { id: 'ex-68', en: 'Consult', tr: 'Başvurmak, danışmak' },
      { id: 'ex-69', en: 'Contain', tr: 'Kapsamak, içermek' },
      { id: 'ex-70', en: 'Contend', tr: 'Uğraşmak, çekişmek' },
      { id: 'ex-71', en: 'Contradict', tr: 'Çelişmek' },
      { id: 'ex-72', en: 'Control', tr: 'Kontrol etmek' },
      { id: 'ex-73', en: 'Convert', tr: 'Dönüştürmek' },
      { id: 'ex-74', en: 'Convince', tr: 'İkna etmek' },
      { id: 'ex-75', en: 'Counter', tr: 'Karşı çıkmak' },
      { id: 'ex-76', en: 'Create', tr: 'Oluşturmak, yaratmak' },
      { id: 'ex-77', en: 'Cultivate', tr: 'Ekip biçmek' },
      { id: 'ex-78', en: 'Curtail', tr: 'Kısaltmak, azaltmak' },
      { id: 'ex-79', en: 'Decide', tr: 'Karar vermek' },
      { id: 'ex-80', en: 'Declare', tr: 'Beyan etmek, ilan etmek' },
      { id: 'ex-81', en: 'Dedicate', tr: 'Adamak' },
      { id: 'ex-82', en: 'Defeat', tr: 'Mağlup etmek, yenmek' },
      { id: 'ex-83', en: 'Defend', tr: 'Savunmak' },
      { id: 'ex-84', en: 'Delay', tr: 'Ertelemek' },
      { id: 'ex-85', en: 'Delete', tr: 'Silmek' },
      { id: 'ex-86', en: 'Deliver', tr: 'Teslim etmek' },
      { id: 'ex-87', en: 'Demand', tr: 'Talep etmek, istemek' },
      { id: 'ex-88', en: 'Demonstrate', tr: 'Göstermek, kanıtlamak' },
      { id: 'ex-89', en: 'Deny', tr: 'İnkar etmek' },
      { id: 'ex-90', en: 'Derive', tr: 'Türemek, kaynaklanmak' },
      { id: 'ex-91', en: 'Descend', tr: 'İnmek, alçalmak' },
      { id: 'ex-92', en: 'Designate', tr: 'Atamak, belirlemek' },
      { id: 'ex-93', en: 'Destroy', tr: 'Tahrip etmek, yıkmak' },
      { id: 'ex-94', en: 'Detect', tr: 'Keşfetmek, belirlemek' },
      { id: 'ex-95', en: 'Deter', tr: 'Caydırmak' },
      { id: 'ex-96', en: 'Deteriorate', tr: 'Bozulmak, fenalaşmak' },
      { id: 'ex-97', en: 'Determine', tr: 'Belirlemek' },
      { id: 'ex-98', en: 'Differ', tr: 'Farklı olmak' },
      { id: 'ex-99', en: 'Differentiate', tr: 'Farklılaştırmak' },
      { id: 'ex-100', en: 'Diminish', tr: 'Azalmak' },
      { id: 'ex-101', en: 'Disapprove', tr: 'Onaylamamak' },
      { id: 'ex-102', en: 'Discover', tr: 'Keşfetmek' },
      { id: 'ex-103', en: 'Discriminate', tr: 'Ayrımcılık yapmak' },
      { id: 'ex-104', en: 'Dislike', tr: 'Hoşlanmamak' },
      { id: 'ex-105', en: 'Dismiss', tr: 'Kovmak, reddetmek' },
      { id: 'ex-106', en: 'Dispel', tr: 'Dağıtmak, defetmek' },
      { id: 'ex-107', en: 'Display', tr: 'Göstermek, sergilemek' },
      { id: 'ex-108', en: 'Disrupt', tr: 'Bozmak, aksatmak' },
      { id: 'ex-109', en: 'Dissolve', tr: 'Eritmek, çözmek' },
      { id: 'ex-110', en: 'Distinguish', tr: 'Ayırmak, ayırt etmek' },
      { id: 'ex-111', en: 'Distract', tr: 'Dikkatini dağıtmak' },
      { id: 'ex-112', en: 'Disturb', tr: 'Rahatsız etmek' },
      { id: 'ex-113', en: 'Divide', tr: 'Bölmek' },
      { id: 'ex-114', en: 'Elaborate', tr: 'Detaylandırmak' },
      { id: 'ex-115', en: 'Eliminate', tr: 'Elemek, ortadan kaldırmak' },
      { id: 'ex-116', en: 'Embody', tr: 'Somutlaştırmak, simgelemek' },
      { id: 'ex-117', en: 'Emigrate', tr: 'Göç etmek' },
      { id: 'ex-118', en: 'Employ', tr: 'Kullanmak, işe almak' },
      { id: 'ex-119', en: 'Encompass', tr: 'Kuşatmak, kapsamak' },
      { id: 'ex-120', en: 'Endure', tr: 'Katlanmak, dayanmak' },
      { id: 'ex-121', en: 'Enforce', tr: 'Uygulamak, zorlamak' },
      { id: 'ex-122', en: 'Enhance', tr: 'Arttırmak, geliştirmek' },
      { id: 'ex-123', en: 'Ensure', tr: 'Sağlamak, garantiye almak' },
      { id: 'ex-124', en: 'Entertain', tr: 'Eğlendirmek' },
      { id: 'ex-125', en: 'Entitle', tr: 'Yetki vermek, isimlendirmek' },
      { id: 'ex-126', en: 'Envisage', tr: 'Öngörmek, tahmin etmek' },
      { id: 'ex-127', en: 'Eradicate', tr: 'Yok etmek, kökünü kurutmak' },
      { id: 'ex-128', en: 'Escalate', tr: 'Kızışmak, yükselmek' },
      { id: 'ex-129', en: 'Estimate', tr: 'Tahmin etmek' },
      { id: 'ex-130', en: 'Evacuate', tr: 'Tahliye etmek' },
      { id: 'ex-131', en: 'Evoke', tr: 'Anımsatmak, uyandırmak' },
      { id: 'ex-132', en: 'Exaggerate', tr: 'Abartmak' },
      { id: 'ex-133', en: 'Examine', tr: 'İncelemek' },
      { id: 'ex-134', en: 'Excavate', tr: 'Kazı yapmak' },
      { id: 'ex-135', en: 'Exceed', tr: 'Aşmak, geçmek' },
      { id: 'ex-136', en: 'Exchange', tr: 'Takas etmek' },
      { id: 'ex-137', en: 'Exclude', tr: 'Dışlamak, hariç tutmak' },
      { id: 'ex-138', en: 'Exhaust', tr: 'Yormak, tüketmek' },
      { id: 'ex-139', en: 'Exist', tr: 'Var olmak' },
      { id: 'ex-140', en: 'Expand', tr: 'Genişletmek' },
      { id: 'ex-141', en: 'Expire', tr: 'Süresi dolmak' },
      { id: 'ex-142', en: 'Explain', tr: 'Açıklamak' },
      { id: 'ex-143', en: 'Exploit', tr: 'Sömürmek, kullanmak' },
      { id: 'ex-144', en: 'Expose', tr: 'Maruz bırakmak' },
      { id: 'ex-145', en: 'Extend', tr: 'Uzatmak, genişletmek' },
      { id: 'ex-146', en: 'Extract', tr: 'Çıkarmak, özünü almak' },
      { id: 'ex-147', en: 'Facilitate', tr: 'Kolaylaştırmak, hafifletmek' },
      { id: 'ex-148', en: 'Fail', tr: 'Başarısız olmak' },
      { id: 'ex-149', en: 'Find', tr: 'Bulmak' },
      { id: 'ex-150', en: 'Fix', tr: 'Onarmak, tamir etmek' },
      { id: 'ex-151', en: 'Fluctuate', tr: 'Dalgalanmak' },
      { id: 'ex-152', en: 'Focus', tr: 'Odaklanmak' },
      { id: 'ex-153', en: 'Force', tr: 'Zorlamak, baskı yapmak' },
      { id: 'ex-154', en: 'Foresee', tr: 'Öngörmek' },
      { id: 'ex-155', en: 'Fortify', tr: 'Güçlendirmek, desteklemek' },
      { id: 'ex-156', en: 'Foster', tr: 'Teşvik etmek, beslemek' },
      { id: 'ex-157', en: 'Fulfill', tr: 'Yerine getirmek' },
      { id: 'ex-158', en: 'Grow', tr: 'Büyümek, yetişmek' },
      { id: 'ex-159', en: 'Guess', tr: 'Tahmin etmek' },
      { id: 'ex-160', en: 'Halt', tr: 'Durdurmak' },
      { id: 'ex-161', en: 'Hamper', tr: 'Engellemek, kösteklemek' },
      { id: 'ex-162', en: 'Happen', tr: 'Meydana gelmek, olmak' },
      { id: 'ex-163', en: 'Help', tr: 'Yardım etmek' },
      { id: 'ex-164', en: 'Herald', tr: 'Müjdelemek, ilan etmek' },
      { id: 'ex-165', en: 'Highlight', tr: 'Vurgulamak, altını çizmek' },
      { id: 'ex-166', en: 'Hinder', tr: 'Engellemek' },
      { id: 'ex-167', en: 'Host', tr: 'Ağırlamak, ev sahipliği yapmak' },
      { id: 'ex-168', en: 'Identify', tr: 'Kimliğini tespit etmek, tanımlamak' },
      { id: 'ex-169', en: 'Ignore', tr: 'Görmezden gelmek' },
      { id: 'ex-170', en: 'Impair', tr: 'Bozmak, zarar vermek' },
      { id: 'ex-171', en: 'Implement', tr: 'Uygulamak' },
      { id: 'ex-172', en: 'Imply', tr: 'İma etmek, kastetmek' },
      { id: 'ex-173', en: 'Improve', tr: 'Geliştirmek, iyileştirmek' },
      { id: 'ex-174', en: 'Include', tr: 'İçermek' },
      { id: 'ex-175', en: 'Incorporate', tr: 'Birleştirmek, bünyesine katmak' },
      { id: 'ex-176', en: 'Induce', tr: 'İkna etmek, neden olmak' },
      { id: 'ex-177', en: 'Influence', tr: 'Etkilemek' },
      { id: 'ex-178', en: 'Inhabit', tr: 'İkamet etmek, yaşamak' },
      { id: 'ex-179', en: 'Inherit', tr: 'Miras almak' },
      { id: 'ex-180', en: 'Initiate', tr: 'Başlatmak' },
      { id: 'ex-181', en: 'Insist', tr: 'Israr etmek' },
      { id: 'ex-182', en: 'Inspire', tr: 'İlham vermek' },
      { id: 'ex-183', en: 'Interact', tr: 'Etkileşime girmek' },
      { id: 'ex-184', en: 'Interrupt', tr: 'Sözünü kesmek, araya girmek' },
      { id: 'ex-185', en: 'Introduce', tr: 'Tanıtmak, tanıştırmak' },
      { id: 'ex-186', en: 'Involve', tr: 'İçermek, kapsamak' },
      { id: 'ex-187', en: 'Jeopardize', tr: 'Tehlikeye atmak' },
      { id: 'ex-188', en: 'Launch', tr: 'Başlatmak, fırlatmak' },
      { id: 'ex-189', en: 'Lead', tr: 'Yönetmek, öncülük etmek' },
      { id: 'ex-190', en: 'Leave', tr: 'Ayrılmak, bırakmak' },
      { id: 'ex-191', en: 'Lose', tr: 'Kaybetmek' },
      { id: 'ex-192', en: 'Lower', tr: 'Düşürmek, alçaltmak' },
      { id: 'ex-193', en: 'Magnify', tr: 'Büyütmek, övmek' },
      { id: 'ex-194', en: 'Maintain', tr: 'Sürdürmek, bakım yapmak' },
      { id: 'ex-195', en: 'Mandate', tr: 'Emretmek, zorunlu kılmak' },
      { id: 'ex-196', en: 'Manifest', tr: 'Açıkça göstermek' },
      { id: 'ex-197', en: 'Mitigate', tr: 'Hafifletmek, azaltmak' },
      { id: 'ex-198', en: 'Narrow', tr: 'Daralmak, daraltmak' },
      { id: 'ex-199', en: 'Neglect', tr: 'İhmal etmek' },
      { id: 'ex-200', en: 'Nourish', tr: 'Beslemek' },
      { id: 'ex-201', en: 'Object', tr: 'İtiraz etmek' },
      { id: 'ex-202', en: 'Obtain', tr: 'Elde etmek' },
      { id: 'ex-203', en: 'Occupy', tr: 'İşgal etmek, meşgul etmek' },
      { id: 'ex-204', en: 'Occur', tr: 'Meydana gelmek' },
      { id: 'ex-205', en: 'Offend', tr: 'Rencide etmek, suç işlemek' },
      { id: 'ex-206', en: 'Offer', tr: 'Teklif etmek, sunmak' },
      { id: 'ex-207', en: 'Omit', tr: 'Dahil etmemek, atlamak' },
      { id: 'ex-208', en: 'Open', tr: 'Açmak' },
      { id: 'ex-209', en: 'Operate', tr: 'İşletmek, çalıştırmak' },
      { id: 'ex-210', en: 'Oppress', tr: 'Baskı yapmak, eziyet etmek' },
      { id: 'ex-211', en: 'Originate', tr: 'Kaynaklanmak' },
      { id: 'ex-212', en: 'Outweigh', tr: 'Daha ağır basmak' },
      { id: 'ex-213', en: 'Overcome', tr: 'Üstesinden gelmek' },
      { id: 'ex-214', en: 'Overestimate', tr: 'Gözünde büyütmek' },
      { id: 'ex-215', en: 'Overlook', tr: 'Gözden kaçırmak' },
      { id: 'ex-216', en: 'Overtake', tr: 'Sollamak, yetişip geçmek' },
      { id: 'ex-217', en: 'Penetrate', tr: 'Nüfuz etmek, girmek' },
      { id: 'ex-218', en: 'Perform', tr: 'Gerçekleştirmek, uygulamak' },
      { id: 'ex-219', en: 'Perpetuate', tr: 'Sürdürmek, devam ettirmek' },
      { id: 'ex-220', en: 'Persuade', tr: 'İkna etmek' },
      { id: 'ex-221', en: 'Pinpoint', tr: 'Tam yerini belirlemek' },
      { id: 'ex-222', en: 'Plunder', tr: 'Yağmalamak' },
      { id: 'ex-223', en: 'Pollute', tr: 'Kirletmek' },
      { id: 'ex-224', en: 'Postpone', tr: 'Ertelemek' },
      { id: 'ex-225', en: 'Precede', tr: 'Önce gelmek' },
      { id: 'ex-226', en: 'Predict', tr: 'Tahmin etmek' },
      { id: 'ex-227', en: 'Pretend', tr: 'Gibi yapmak' },
      { id: 'ex-228', en: 'Prevent', tr: 'Önlemek, engellemek' },
      { id: 'ex-229', en: 'Progress', tr: 'İlerlemek, gelişmek' },
      { id: 'ex-230', en: 'Prohibit', tr: 'Yasaklamak' },
      { id: 'ex-231', en: 'Prolong', tr: 'Uzatmak' },
      { id: 'ex-232', en: 'Promise', tr: 'Söz vermek' },
      { id: 'ex-233', en: 'Promote', tr: 'Desteklemek, terfi ettirmek' },
      { id: 'ex-234', en: 'Protect', tr: 'Korumak' },
      { id: 'ex-235', en: 'Provide', tr: 'Sağlamak' },
      { id: 'ex-236', en: 'Provoke', tr: 'Kışkırtmak' },
      { id: 'ex-237', en: 'Purchase', tr: 'Satın almak' },
      { id: 'ex-238', en: 'Qualify', tr: 'Nitelendirmek, hak kazanmak' },
      { id: 'ex-239', en: 'Quarrel', tr: 'Tartışmak, kavga etmek' },
      { id: 'ex-240', en: 'Quit', tr: 'Bırakmak, çıkmak' },
      { id: 'ex-241', en: 'Raise', tr: 'Yükseltmek, arttırmak' },
      { id: 'ex-242', en: 'Realise', tr: 'Fark etmek' },
      { id: 'ex-243', en: 'Receive', tr: 'Almak' },
      { id: 'ex-244', en: 'Recognise', tr: 'Tanımak' },
      { id: 'ex-245', en: 'Recommend', tr: 'Tavsiye etmek' },
      { id: 'ex-246', en: 'Recount', tr: 'Anlatmak, nakletmek' },
      { id: 'ex-247', en: 'Recover', tr: 'İyileşmek, kurtarmak' },
      { id: 'ex-248', en: 'Recruit', tr: 'İşe almak' },
      { id: 'ex-249', en: 'Recycle', tr: 'Geri dönüştürmek' },
      { id: 'ex-250', en: 'Reduce', tr: 'Azaltmak' },
      { id: 'ex-251', en: 'Regard', tr: 'Saymak, hesaba katmak' },
      { id: 'ex-252', en: 'Regret', tr: 'Pişman olmak' },
      { id: 'ex-253', en: 'Regulate', tr: 'Düzenlemek' },
      { id: 'ex-254', en: 'Rehearse', tr: 'Prova yapmak' },
      { id: 'ex-255', en: 'Reject', tr: 'Reddetmek' },
      { id: 'ex-256', en: 'Release', tr: 'Serbest bırakmak, yayınlamak' },
      { id: 'ex-257', en: 'Relieve', tr: 'Rahatlatmak' },
      { id: 'ex-258', en: 'Remain', tr: 'Kalmak, sürdürmek' },
      { id: 'ex-259', en: 'Remove', tr: 'Kaldırmak' },
      { id: 'ex-260', en: 'Renew', tr: 'Yenilemek' },
      { id: 'ex-261', en: 'Replace', tr: 'Yerine koymak, değiştirmek' },
      { id: 'ex-262', en: 'Replenish', tr: 'Yeniden doldurmak, tazelemek' },
      { id: 'ex-263', en: 'Require', tr: 'Gerektirmek' },
      { id: 'ex-264', en: 'Resign', tr: 'Istifa etmek' },
      { id: 'ex-265', en: 'Resist', tr: 'Direnmek' },
      { id: 'ex-266', en: 'Resolve', tr: 'Çözmek' },
      { id: 'ex-267', en: 'Respect', tr: 'Saygı duymak' },
      { id: 'ex-268', en: 'Respond', tr: 'Yanıt vermek' },
      { id: 'ex-269', en: 'Restrain', tr: 'Dizginlemek, engellemek' },
      { id: 'ex-270', en: 'Restrict', tr: 'Kısıtlamak' },
      { id: 'ex-271', en: 'Retain', tr: 'Muhafaza etmek, sürdürmek' },
      { id: 'ex-272', en: 'Retrieve', tr: 'Geri almak' },
      { id: 'ex-273', en: 'Return', tr: 'Dönmek, iade etmek' },
      { id: 'ex-274', en: 'Reveal', tr: 'Ortaya çıkarmak' },
      { id: 'ex-275', en: 'Reverse', tr: 'Tersine çevirmek' },
      { id: 'ex-276', en: 'Review', tr: 'Gözden geçirmek' },
      { id: 'ex-277', en: 'Revive', tr: 'Canlandırmak' },
      { id: 'ex-278', en: 'Revolutionise', tr: 'Devrim yapmak, köklü değiştirmek' },
      { id: 'ex-279', en: 'Ruin', tr: 'Mahvetmek' },
      { id: 'ex-280', en: 'Seek', tr: 'Aramak' },
      { id: 'ex-281', en: 'Seize', tr: 'Kavramak, el koymak' },
      { id: 'ex-282', en: 'Select', tr: 'Seçmek' },
      { id: 'ex-283', en: 'Sentence', tr: 'Hüküm giydirmek' },
      { id: 'ex-284', en: 'Show', tr: 'Göstermek' },
      { id: 'ex-285', en: 'Specify', tr: 'Belirtmek' },
      { id: 'ex-286', en: 'Speculate', tr: 'Tahmin yürütmek' },
      { id: 'ex-287', en: 'Spoil', tr: 'Bozmak, şımartmak' },
      { id: 'ex-288', en: 'Spread', tr: 'Yaymak' },
      { id: 'ex-289', en: 'Start', tr: 'Başlamak' },
      { id: 'ex-290', en: 'Stimulate', tr: 'Uyarmak, teşvik etmek' },
      { id: 'ex-291', en: 'Stretch', tr: 'Uzatmak, esnetmek' },
      { id: 'ex-292', en: 'Suffer', tr: 'Acı çekmek' },
      { id: 'ex-293', en: 'Suggest', tr: 'Önermek' },
      { id: 'ex-294', en: 'Suppress', tr: 'Bastırmak' },
      { id: 'ex-295', en: 'Surpass', tr: 'Aşmak, geçmek' },
      { id: 'ex-296', en: 'Survive', tr: 'Hayatta kalmak' },
      { id: 'ex-297', en: 'Suspect', tr: 'Şüphelenmek' },
      { id: 'ex-298', en: 'Suspend', tr: 'Askıya almak' },
      { id: 'ex-299', en: 'Sustain', tr: 'Sürdürmek' },
      { id: 'ex-300', en: 'Switch', tr: 'Değiştirmek' },
      { id: 'ex-301', en: 'Tackle', tr: 'Ele almak, mücadele etmek' },
      { id: 'ex-302', en: 'Threaten', tr: 'Tehdit etmek' },
      { id: 'ex-303', en: 'Transmit', tr: 'İletmek' },
      { id: 'ex-304', en: 'Treat', tr: 'Davranmak, tedavi etmek' },
      { id: 'ex-305', en: 'Trigger', tr: 'Tetiklemek' },
      { id: 'ex-306', en: 'Underestimate', tr: 'Küçümsemek' },
      { id: 'ex-307', en: 'Undergo', tr: 'Maruz kalmak, geçirmek' },
      { id: 'ex-308', en: 'Undermine', tr: 'Zayıflatmak, baltalamak' },
      { id: 'ex-309', en: 'Underpin', tr: 'Desteklemek' },
      { id: 'ex-310', en: 'Undertake', tr: 'Üstlenmek' },
      { id: 'ex-311', en: 'Unearth', tr: 'Ortaya çıkarmak' },
      { id: 'ex-312', en: 'Unify', tr: 'Birleştirmek' },
      { id: 'ex-313', en: 'Upgrade', tr: 'Yükseltmek, geliştirmek' },
      { id: 'ex-314', en: 'Utilize', tr: 'Kullanmak, yararlanmak' },
      { id: 'ex-315', en: 'Vaccinate', tr: 'Aşılamak' },
      { id: 'ex-316', en: 'Validate', tr: 'Doğrulamak' },
      { id: 'ex-317', en: 'Verify', tr: 'Doğrulamak' },
      { id: 'ex-318', en: 'Violate', tr: 'İhlal etmek' },
      { id: 'ex-319', en: 'Wander', tr: 'Dolaşmak' },
      { id: 'ex-320', en: 'Weaken', tr: 'Zayıflatmak' },
      { id: 'ex-321', en: 'Withdraw', tr: 'Geri çekilmek' },
      { id: 'ex-322', en: 'Worsen', tr: 'Kötüleşmek' },
      { id: 'ex-323', en: 'Yield', tr: 'Ürün vermek, sağlamak, sebep olmak' },
    ]
  }
];
