import { Deck } from './types';

// Large dataset separated into chunks for better organization
export const STARTER_DECKS: Deck[] = [
  {
    id: 'common-1',
    name: 'Temel Kelimeler (1-50)',
    description: 'Günlük hayatta en sık kullanılan ilk 50 kelime.',
    words: [
      { id: '1', en: 'Time', tr: 'Zaman', exampleEn: 'Time flows like a river.', exampleTr: 'Zaman bir nehir gibi akar.' },
      { id: '2', en: 'Person', tr: 'Kişi', exampleEn: 'He is a nice person.', exampleTr: 'O iyi bir kişidir.' },
      { id: '3', en: 'Year', tr: 'Yıl', exampleEn: 'Happy new year!', exampleTr: 'Mutlu yıllar!' },
      { id: '4', en: 'Way', tr: 'Yol / Yöntem', exampleEn: 'Show me the way.', exampleTr: 'Bana yolu göster.' },
      { id: '5', en: 'Day', tr: 'Gün', exampleEn: 'Have a nice day.', exampleTr: 'İyi günler.' },
      { id: '6', en: 'Thing', tr: 'Şey', exampleEn: 'That is a strange thing.', exampleTr: 'Bu garip bir şey.' },
      { id: '7', en: 'Man', tr: 'Adam', exampleEn: 'The man is tall.', exampleTr: 'Adam uzun boylu.' },
      { id: '8', en: 'World', tr: 'Dünya', exampleEn: 'The world is round.', exampleTr: 'Dünya yuvarlaktır.' },
      { id: '9', en: 'Life', tr: 'Hayat', exampleEn: 'Life is beautiful.', exampleTr: 'Hayat güzeldir.' },
      { id: '10', en: 'Hand', tr: 'El', exampleEn: 'Give me your hand.', exampleTr: 'Elini bana ver.' },
      { id: '11', en: 'Part', tr: 'Parça / Bölüm', exampleEn: 'This is the best part.', exampleTr: 'Bu en iyi bölüm.' },
      { id: '12', en: 'Child', tr: 'Çocuk', exampleEn: 'The child is playing.', exampleTr: 'Çocuk oynuyor.' },
      { id: '13', en: 'Eye', tr: 'Göz', exampleEn: 'She has blue eyes.', exampleTr: 'Onun mavi gözleri var.' },
      { id: '14', en: 'Woman', tr: 'Kadın', exampleEn: 'That woman is a doctor.', exampleTr: 'O kadın bir doktor.' },
      { id: '15', en: 'Place', tr: 'Yer', exampleEn: 'This is a nice place.', exampleTr: 'Burası güzel bir yer.' },
      { id: '16', en: 'Work', tr: 'İş / Çalışmak', exampleEn: 'I have a lot of work.', exampleTr: 'Çok işim var.' },
      { id: '17', en: 'Week', tr: 'Hafta', exampleEn: 'See you next week.', exampleTr: 'Haftaya görüşürüz.' },
      { id: '18', en: 'Case', tr: 'Durum / Dava', exampleEn: 'In that case, we leave.', exampleTr: 'O durumda, biz gideriz.' },
      { id: '19', en: 'Point', tr: 'Nokta / Puan', exampleEn: 'What is your point?', exampleTr: 'Amacın (noktan) ne?' },
      { id: '20', en: 'Government', tr: 'Hükümet', exampleEn: 'The government made a law.', exampleTr: 'Hükümet bir yasa yaptı.' },
      { id: '21', en: 'Company', tr: 'Şirket', exampleEn: 'He works for a big company.', exampleTr: 'Büyük bir şirkette çalışıyor.' },
      { id: '22', en: 'Number', tr: 'Sayı / Numara', exampleEn: 'What is your phone number?', exampleTr: 'Telefon numaran nedir?' },
      { id: '23', en: 'Group', tr: 'Grup', exampleEn: 'A group of people arrived.', exampleTr: 'Bir grup insan geldi.' },
      { id: '24', en: 'Problem', tr: 'Sorun', exampleEn: 'We have a big problem.', exampleTr: 'Büyük bir sorunumuz var.' },
      { id: '25', en: 'Fact', tr: 'Gerçek', exampleEn: 'It is a known fact.', exampleTr: 'Bu bilinen bir gerçektir.' },
      { id: '26', en: 'To Be', tr: 'Olmak', exampleEn: 'I want to be happy.', exampleTr: 'Mutlu olmak istiyorum.' },
      { id: '27', en: 'To Have', tr: 'Sahip olmak', exampleEn: 'I have a car.', exampleTr: 'Bir arabam var.' },
      { id: '28', en: 'To Do', tr: 'Yapmak', exampleEn: 'I will do my best.', exampleTr: 'Elimden geleni yapacağım.' },
      { id: '29', en: 'To Say', tr: 'Söylemek', exampleEn: 'What did you say?', exampleTr: 'Ne söyledin?' },
      { id: '30', en: 'To Get', tr: 'Almak / Elde etmek', exampleEn: 'I need to get some sleep.', exampleTr: 'Biraz uyumam (uyku almam) lazım.' },
      { id: '31', en: 'To Make', tr: 'Yapmak (Üretmek)', exampleEn: 'She makes delicious cakes.', exampleTr: 'O lezzetli kekler yapar.' },
      { id: '32', en: 'To Go', tr: 'Gitmek', exampleEn: 'Let\'s go home.', exampleTr: 'Hadi eve gidelim.' },
      { id: '33', en: 'To Know', tr: 'Bilmek', exampleEn: 'I know the answer.', exampleTr: 'Cevabı biliyorum.' },
      { id: '34', en: 'To Take', tr: 'Almak / Götürmek', exampleEn: 'Take this book.', exampleTr: 'Bu kitabı al.' },
      { id: '35', en: 'To See', tr: 'Görmek', exampleEn: 'I can see the sea.', exampleTr: 'Denizi görebiliyorum.' },
      { id: '36', en: 'To Come', tr: 'Gelmek', exampleEn: 'Come here, please.', exampleTr: 'Buraya gel, lütfen.' },
      { id: '37', en: 'To Think', tr: 'Düşünmek', exampleEn: 'I think it will rain.', exampleTr: 'Sanırım (düşünüyorum) yağmur yağacak.' },
      { id: '38', en: 'To Look', tr: 'Bakmak', exampleEn: 'Look at the sky.', exampleTr: 'Gökyüzüne bak.' },
      { id: '39', en: 'To Want', tr: 'İstemek', exampleEn: 'I want some water.', exampleTr: 'Biraz su istiyorum.' },
      { id: '40', en: 'To Give', tr: 'Vermek', exampleEn: 'Give me a chance.', exampleTr: 'Bana bir şans ver.' },
      { id: '41', en: 'Good', tr: 'İyi', exampleEn: 'This is a good book.', exampleTr: 'Bu iyi bir kitap.' },
      { id: '42', en: 'New', tr: 'Yeni', exampleEn: 'I bought a new phone.', exampleTr: 'Yeni bir telefon aldım.' },
      { id: '43', en: 'First', tr: 'İlk', exampleEn: 'She was the first to arrive.', exampleTr: 'O ilk varandı.' },
      { id: '44', en: 'Last', tr: 'Son', exampleEn: 'This is the last bus.', exampleTr: 'Bu son otobüs.' },
      { id: '45', en: 'Long', tr: 'Uzun', exampleEn: 'It was a long journey.', exampleTr: 'Uzun bir yolculuktu.' },
      { id: '46', en: 'Great', tr: 'Harika / Büyük', exampleEn: 'You did a great job.', exampleTr: 'Harika bir iş çıkardın.' },
      { id: '47', en: 'Little', tr: 'Küçük / Az', exampleEn: 'I have a little money.', exampleTr: 'Az param var.' },
      { id: '48', en: 'Own', tr: 'Kendi', exampleEn: 'I have my own room.', exampleTr: 'Kendi odam var.' },
      { id: '49', en: 'Other', tr: 'Diğer', exampleEn: 'Show me the other hand.', exampleTr: 'Diğer elini göster.' },
      { id: '50', en: 'Old', tr: 'Eski / Yaşlı', exampleEn: 'My car is very old.', exampleTr: 'Arabam çok eski.' },
    ]
  },
  {
    id: 'common-2',
    name: 'Orta Seviye Kelimeler',
    description: 'Kendinizi daha iyi ifade etmeniz için gerekenler.',
    words: [
      { id: '51', en: 'Right', tr: 'Doğru / Sağ', exampleEn: 'You are right.', exampleTr: 'Haklısın (Doğrusun).' },
      { id: '52', en: 'Big', tr: 'Büyük', exampleEn: 'New York is a big city.', exampleTr: 'New York büyük bir şehirdir.' },
      { id: '53', en: 'High', tr: 'Yüksek', exampleEn: 'The prices are very high.', exampleTr: 'Fiyatlar çok yüksek.' },
      { id: '54', en: 'Different', tr: 'Farklı', exampleEn: 'I want something different.', exampleTr: 'Farklı bir şey istiyorum.' },
      { id: '55', en: 'Small', tr: 'Küçük', exampleEn: 'The apartment is small.', exampleTr: 'Daire küçük.' },
      { id: '56', en: 'Large', tr: 'Geniş / Büyük', exampleEn: 'They have a large family.', exampleTr: 'Geniş bir aileleri var.' },
      { id: '57', en: 'Next', tr: 'Sonraki', exampleEn: 'See you next time.', exampleTr: 'Bir dahaki sefere görüşürüz.' },
      { id: '58', en: 'Early', tr: 'Erken', exampleEn: 'I woke up early today.', exampleTr: 'Bugün erken uyandım.' },
      { id: '59', en: 'Young', tr: 'Genç', exampleEn: 'He is a young man.', exampleTr: 'O genç bir adam.' },
      { id: '60', en: 'Important', tr: 'Önemli', exampleEn: 'This is an important meeting.', exampleTr: 'Bu önemli bir toplantı.' },
      { id: '61', en: 'Few', tr: 'Az / Birkaç', exampleEn: 'I have a few questions.', exampleTr: 'Birkaç sorum var.' },
      { id: '62', en: 'Public', tr: 'Halka açık / Kamu', exampleEn: 'This is a public park.', exampleTr: 'Bu halka açık bir park.' },
      { id: '63', en: 'Bad', tr: 'Kötü', exampleEn: 'The weather is bad.', exampleTr: 'Hava kötü.' },
      { id: '64', en: 'Same', tr: 'Aynı', exampleEn: 'We have the same car.', exampleTr: 'Aynı arabaya sahibiz.' },
      { id: '65', en: 'Able', tr: 'Muktedir / Yapabilir', exampleEn: 'Will you be able to come?', exampleTr: 'Gelebilecek misin?' },
      { id: '66', en: 'To Use', tr: 'Kullanmak', exampleEn: 'Can I use your phone?', exampleTr: 'Telefonunu kullanabilir miyim?' },
      { id: '67', en: 'To Find', tr: 'Bulmak', exampleEn: 'I cannot find my keys.', exampleTr: 'Anahtarlarımı bulamıyorum.' },
      { id: '68', en: 'To Tell', tr: 'Anlatmak / Söylemek', exampleEn: 'Tell me the truth.', exampleTr: 'Bana gerçeği söyle.' },
      { id: '69', en: 'To Ask', tr: 'Sormak / İstemek', exampleEn: 'Can I ask a question?', exampleTr: 'Bir soru sorabilir miyim?' },
      { id: '70', en: 'To Work', tr: 'Çalışmak', exampleEn: 'She works at a bank.', exampleTr: 'O bir bankada çalışıyor.' },
      { id: '71', en: 'To Seem', tr: 'Görünmek', exampleEn: 'You seem tired.', exampleTr: 'Yorgun görünüyorsun.' },
      { id: '72', en: 'To Feel', tr: 'Hissetmek', exampleEn: 'I feel much better.', exampleTr: 'Çok daha iyi hissediyorum.' },
      { id: '73', en: 'To Try', tr: 'Denemek', exampleEn: 'Try to do it again.', exampleTr: 'Tekrar yapmayı dene.' },
      { id: '74', en: 'To Leave', tr: 'Ayrılmak / Bırakmak', exampleEn: 'Don\'t leave me alone.', exampleTr: 'Beni yalnız bırakma.' },
      { id: '75', en: 'To Call', tr: 'Aramak / Çağırmak', exampleEn: 'Call me later.', exampleTr: 'Beni sonra ara.' },
      { id: '76', en: 'Beneath', tr: 'Altında', exampleEn: 'The boat sank beneath the waves.', exampleTr: 'Tekne dalgaların altına battı.' },
      { id: '77', en: 'Education', tr: 'Eğitim', exampleEn: 'Education is very important.', exampleTr: 'Eğitim çok önemlidir.' },
      { id: '78', en: 'Opportunity', tr: 'Fırsat', exampleEn: 'Don\'t miss this opportunity.', exampleTr: 'Bu fırsatı kaçırma.' },
      { id: '79', en: 'Society', tr: 'Toplum', exampleEn: 'We live in a society.', exampleTr: 'Bir toplumda yaşıyoruz.' },
      { id: '80', en: 'Process', tr: 'Süreç', exampleEn: 'Learning is a slow process.', exampleTr: 'Öğrenme yavaş bir süreçtir.' },
      { id: '81', en: 'Voice', tr: 'Ses', exampleEn: 'She has a beautiful voice.', exampleTr: 'Onun güzel bir sesi var.' },
      { id: '82', en: 'Value', tr: 'Değer', exampleEn: 'What is the value of this?', exampleTr: 'Bunun değeri nedir?' },
      { id: '83', en: 'Action', tr: 'Eylem / Hareket', exampleEn: 'Take action now.', exampleTr: 'Şimdi harekete geç.' },
      { id: '84', en: 'Area', tr: 'Alan / Bölge', exampleEn: 'This is a restricted area.', exampleTr: 'Bu yasaklanmış bir bölge.' },
      { id: '85', en: 'Evidence', tr: 'Kanıt', exampleEn: 'There is no evidence.', exampleTr: 'Hiçbir kanıt yok.' },
      { id: '86', en: 'Effect', tr: 'Etki', exampleEn: 'The medicine had no effect.', exampleTr: 'İlacın hiçbir etkisi olmadı.' },
      { id: '87', en: 'Support', tr: 'Destek', exampleEn: 'I need your support.', exampleTr: 'Desteğine ihtiyacım var.' },
      { id: '88', en: 'Moment', tr: 'An', exampleEn: 'Wait a moment.', exampleTr: 'Bir saniye bekle.' },
      { id: '89', en: 'Sense', tr: 'His / Duyu', exampleEn: 'It makes no sense.', exampleTr: 'Bunun hiçbir mantığı yok.' },
      { id: '90', en: 'Material', tr: 'Malzeme', exampleEn: 'What material is this?', exampleTr: 'Bu hangi malzeme?' },
    ]
  },
  {
    id: 'common-3',
    name: 'İleri Seviye Kelimeler',
    description: 'Akademik ve profesyonel kelimeler.',
    words: [
      { id: '91', en: 'To Provide', tr: 'Sağlamak / Temin etmek', exampleEn: 'We provide food for the poor.', exampleTr: 'Fakirlere yemek sağlıyoruz.' },
      { id: '92', en: 'To Include', tr: 'İçermek', exampleEn: 'The price includes breakfast.', exampleTr: 'Fiyata kahvaltı dahildir.' },
      { id: '93', en: 'To Continue', tr: 'Devam etmek', exampleEn: 'Please continue working.', exampleTr: 'Lütfen çalışmaya devam edin.' },
      { id: '94', en: 'To Set', tr: 'Ayarlamak / Kurmak', exampleEn: 'Set the alarm for 7 AM.', exampleTr: 'Alarmı sabah 7\'ye kur.' },
      { id: '95', en: 'To Learn', tr: 'Öğrenmek', exampleEn: 'I want to learn English.', exampleTr: 'İngilizce öğrenmek istiyorum.' },
      { id: '96', en: 'To Change', tr: 'Değiştirmek', exampleEn: 'You cannot change the past.', exampleTr: 'Geçmişi değiştiremezsin.' },
      { id: '97', en: 'To Lead', tr: 'Yönetmek / Öncülük etmek', exampleEn: 'Who will lead the team?', exampleTr: 'Takıma kim liderlik edecek?' },
      { id: '98', en: 'To Understand', tr: 'Anlamak', exampleEn: 'Do you understand me?', exampleTr: 'Beni anlıyor musun?' },
      { id: '99', en: 'To Watch', tr: 'İzlemek', exampleEn: 'We watched a movie.', exampleTr: 'Bir film izledik.' },
      { id: '100', en: 'To Follow', tr: 'Takip etmek', exampleEn: 'Follow the car.', exampleTr: 'Arabayı takip et.' },
      { id: '101', en: 'Result', tr: 'Sonuç', exampleEn: 'The result was good.', exampleTr: 'Sonuç iyiydi.' },
      { id: '102', en: 'Development', tr: 'Gelişim', exampleEn: 'Economic development is slow.', exampleTr: 'Ekonomik gelişim yavaş.' },
      { id: '103', en: 'Decision', tr: 'Karar', exampleEn: 'Make a decision.', exampleTr: 'Bir karar ver.' },
      { id: '104', en: 'Position', tr: 'Pozisyon / Konum', exampleEn: 'What is your position in the company?', exampleTr: 'Şirketteki pozisyonun nedir?' },
      { id: '105', en: 'Relationship', tr: 'İlişki', exampleEn: 'They have a good relationship.', exampleTr: 'İyi bir ilişkileri var.' },
      { id: '106', en: 'Major', tr: 'Ana / Büyük', exampleEn: 'This is a major problem.', exampleTr: 'Bu büyük bir sorun.' },
      { id: '107', en: 'Specific', tr: 'Belirli / Özel', exampleEn: 'Be more specific.', exampleTr: 'Daha belirgin ol.' },
      { id: '108', en: 'International', tr: 'Uluslararası', exampleEn: 'It is an international airport.', exampleTr: 'O uluslararası bir havaalanı.' },
      { id: '109', en: 'Effective', tr: 'Etkili', exampleEn: 'The medicine is effective.', exampleTr: 'İlaç etkili.' },
      { id: '110', en: 'Various', tr: 'Çeşitli', exampleEn: 'There are various reasons.', exampleTr: 'Çeşitli sebepler var.' },
    ]
  },
  {
    id: 'verbs-1',
    name: 'Fiiller (Verbs)',
    description: 'Hareket ve eylem bildiren kelimeler.',
    words: [
       { id: 'v1', en: 'Accept', tr: 'Kabul etmek', exampleEn: 'She accepted the gift.', exampleTr: 'Hediyeyi kabul etti.' },
       { id: 'v2', en: 'Achieve', tr: 'Başarmak', exampleEn: 'You can achieve your goals.', exampleTr: 'Hedeflerini başarabilirsin.' },
       { id: 'v3', en: 'Admit', tr: 'İtiraf etmek', exampleEn: 'He admitted his mistake.', exampleTr: 'Hatasını itiraf etti.' },
       { id: 'v4', en: 'Affect', tr: 'Etkilemek', exampleEn: 'The weather affects my mood.', exampleTr: 'Hava ruh halimi etkiler.' },
       { id: 'v5', en: 'Afford', tr: 'Gücü yetmek (maddi)', exampleEn: 'I can\'t afford this car.', exampleTr: 'Bu arabaya gücüm yetmez.' },
       { id: 'v6', en: 'Agree', tr: 'Katılmak / Anlaşmak', exampleEn: 'I agree with you.', exampleTr: 'Sana katılıyorum.' },
       { id: 'v7', en: 'Allow', tr: 'İzin vermek', exampleEn: 'Pets are not allowed.', exampleTr: 'Evcil hayvanlara izin verilmez.' },
       { id: 'v8', en: 'Answer', tr: 'Cevap vermek', exampleEn: 'Answer the question.', exampleTr: 'Soruyu cevapla.' },
       { id: 'v9', en: 'Apply', tr: 'Başvurmak / Uygulamak', exampleEn: 'Apply for the job.', exampleTr: 'İşe başvur.' },
       { id: 'v10', en: 'Argue', tr: 'Tartışmak', exampleEn: 'They argue all the time.', exampleTr: 'Sürekli tartışıyorlar.' },
       { id: 'v11', en: 'Arrive', tr: 'Varmak', exampleEn: 'We arrived late.', exampleTr: 'Geç vardık.' },
       { id: 'v12', en: 'Assume', tr: 'Varsaymak', exampleEn: 'I assume you are busy.', exampleTr: 'Meşgul olduğunu varsayıyorum.' },
       { id: 'v13', en: 'Attack', tr: 'Saldırmak', exampleEn: 'The dog attacked him.', exampleTr: 'Köpek ona saldırdı.' },
       { id: 'v14', en: 'Avoid', tr: 'Kaçınmak', exampleEn: 'Avoid junk food.', exampleTr: 'Abur cuburdan kaçın.' },
       { id: 'v15', en: 'Become', tr: 'Olmak / Dönüşmek', exampleEn: 'She became a doctor.', exampleTr: 'O doktor oldu.' },
       { id: 'v16', en: 'Begin', tr: 'Başlamak', exampleEn: 'Let\'s begin the meeting.', exampleTr: 'Toplantıya başlayalım.' },
       { id: 'v17', en: 'Believe', tr: 'İnanmak', exampleEn: 'I believe in you.', exampleTr: 'Sana inanıyorum.' },
       { id: 'v18', en: 'Build', tr: 'İnşa etmek', exampleEn: 'They built a house.', exampleTr: 'Bir ev inşa ettiler.' },
       { id: 'v19', en: 'Buy', tr: 'Satın almak', exampleEn: 'I want to buy bread.', exampleTr: 'Ekmek satın almak istiyorum.' },
       { id: 'v20', en: 'Care', tr: 'Umursamak / Bakım yapmak', exampleEn: 'I don\'t care.', exampleTr: 'Umurumda değil.' },
    ]
  },
  {
    id: 'adjectives-1',
    name: 'Sıfatlar (Adjectives)',
    description: 'Niteleme ve betimleme kelimeleri.',
    words: [
      { id: 'a1', en: 'Available', tr: 'Mevcut / Müsait', exampleEn: 'Is this seat available?', exampleTr: 'Bu koltuk müsait mi?' },
      { id: 'a2', en: 'Beautiful', tr: 'Güzel', exampleEn: 'It is a beautiful day.', exampleTr: 'Güzel bir gün.' },
      { id: 'a3', en: 'Best', tr: 'En iyi', exampleEn: 'He is my best friend.', exampleTr: 'O benim en iyi arkadaşım.' },
      { id: 'a4', en: 'Better', tr: 'Daha iyi', exampleEn: 'I feel better now.', exampleTr: 'Şimdi daha iyi hissediyorum.' },
      { id: 'a5', en: 'Black', tr: 'Siyah', exampleEn: 'She wore a black dress.', exampleTr: 'Siyah bir elbise giydi.' },
      { id: 'a6', en: 'Blue', tr: 'Mavi', exampleEn: 'The sky is blue.', exampleTr: 'Gökyüzü mavi.' },
      { id: 'a7', en: 'Boring', tr: 'Sıkıcı', exampleEn: 'The movie was boring.', exampleTr: 'Film sıkıcıydı.' },
      { id: 'a8', en: 'Brave', tr: 'Cesur', exampleEn: 'He is a brave soldier.', exampleTr: 'O cesur bir asker.' },
      { id: 'a9', en: 'Bright', tr: 'Parlak / Zeki', exampleEn: 'The sun is bright.', exampleTr: 'Güneş parlak.' },
      { id: 'a10', en: 'Busy', tr: 'Meşgul', exampleEn: 'I am very busy.', exampleTr: 'Çok meşgulüm.' },
      { id: 'a11', en: 'Calm', tr: 'Sakin', exampleEn: 'Stay calm.', exampleTr: 'Sakin ol.' },
      { id: 'a12', en: 'Careful', tr: 'Dikkatli', exampleEn: 'Be careful driving.', exampleTr: 'Araba sürerken dikkatli ol.' },
      { id: 'a13', en: 'Certain', tr: 'Kesin', exampleEn: 'Are you certain?', exampleTr: 'Emin misin?' },
      { id: 'a14', en: 'Cheap', tr: 'Ucuz', exampleEn: 'This shirt is cheap.', exampleTr: 'Bu gömlek ucuz.' },
      { id: 'a15', en: 'Clean', tr: 'Temiz', exampleEn: 'Keep your room clean.', exampleTr: 'Odanı temiz tut.' },
      { id: 'a16', en: 'Clear', tr: 'Net / Açık', exampleEn: 'The water is clear.', exampleTr: 'Su berrak.' },
      { id: 'a17', en: 'Close', tr: 'Yakın / Kapalı', exampleEn: 'They are close friends.', exampleTr: 'Onlar yakın arkadaşlar.' },
      { id: 'a18', en: 'Cold', tr: 'Soğuk', exampleEn: 'It is cold outside.', exampleTr: 'Dışarısı soğuk.' },
      { id: 'a19', en: 'Common', tr: 'Yaygın / Ortak', exampleEn: 'Smith is a common name.', exampleTr: 'Smith yaygın bir isimdir.' },
      { id: 'a20', en: 'Complete', tr: 'Tam / Eksiksiz', exampleEn: 'The work is complete.', exampleTr: 'İş tamamlandı.' },
    ]
  }
];